-d /home/fayz/Digital-Design/FPGA_Projects/VGA_Projects/VGA_Bouncing_Square/moving block/impl/gwsynthesis/moving block.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst /home/fayz/Digital-Design/FPGA_Projects/VGA_Projects/VGA_Bouncing_Square/moving block/src/moving block.cst
-cfg /home/fayz/Digital-Design/FPGA_Projects/VGA_Projects/VGA_Bouncing_Square/moving block/impl/pnr/device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
